version: '3.8'

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: postgres_test
    env_file:
      - .env.test
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12345}
      POSTGRES_DB: ${DB_NAME:-visit_test}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    #      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app_network_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-visit_test}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app-test:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
      target: test
    container_name: go_app_test
    env_file:
      - .env.test
    environment:
      DB_HOST: ${DB_HOST:-localhost}
      DB_PORT: ${DB_PORT:-5433}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-12345}
      DB_NAME: ${DB_NAME:-visit_test}
      DB_SSL_MODE: disable
      APP_ENV: ${APP_ENV:-development}
      LOG_LEVEL: ${LOG_LEVEL:-debug}
    ports:
      - "8082:8082"
      - "2345:2345"
    volumes:
      - ./:/app
      - go_mod_cache:/go/pkg/mod
    depends_on:
      postgres-test:
        condition: service_healthy
    networks:
      - app_network_test
    restart: unless-stopped
    security_opt:
      - "seccomp:unconfined"  # Необходимо для delve
    cap_add:
      - SYS_PTRACE
    stdin_open: true
    tty: true
    command: >
      sh -c "
        go test ./... -count=1 -v
      "

volumes:
  postgres_test_data:
  go_mod_cache:

networks:
  app_network_test:
    driver: bridge